# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: soil-standard-spread

on:
  push:
    branches: [ soil-standard-spread ]
  pull_request:
    branches: [ soil-standard-spread ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: repository-snapshot
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn --batch-mode deploy -f ./soil-standard-spread/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.PROJECT_HOLDER_ACCOUNT }}
          MAVEN_PASSWORD: ${{ secrets.PROJECT_HOLDER_PASSWORD }}
